#!/usr/bin/env bash

alias 7='7cmd'
function 7cmd() {

    if [ "$1" == "install" ]; then
        echo "install"
    else
        echo '7lab'
        PROJECT_DIR=$(pwd)
        DOCKER_DIR="7lab-docker"

        if [ -d $DOCKER_DIR ]; then
            cd $DOCKER_DIR
            bash vessel "$PROJECT_DIR" "$@"
            cd $PROJECT_DIR
        else
            echo -e "\033[31mNo '$DOCKER_DIR' directory found within current working directory '$PROJECT_DIR'\033[0m"
        fi

    fi
}