#!/usr/bin/env bash

function initproject() {

    mkdir "$1"
    cd "$1"
    git init
    git add -A && git commit -m "Initial commit"

}

function success() {
    echo -e "\033[1m\033[32mInstallation completed!\033[0m"
}

cd $1

if [ "$3" == "" ]; then
    
    echo -e "\033[31mNo project name is specified! Correct usage: 7 install [framework] [project_name]\033[0m"

elif [ "$2" == "laravel" ]; then
    
    echo "install laravel"
    initproject $3
    echo "hoi"
    # git clone https://github.com/laravel/laravel.git ./
    # cd working/laravel-master
    # composer install
    # success

elif [ "$2" == "wordpress" ]; then

    echo "install wordpress"
    initproject $3
    success


elif [ "$2" == "none" ]; then

    echo "install empty project"
    initproject $3
    success

else

    echo -e "\033[31mThis framework not supported! Supported frameworks are: none, laravel and wordpress\033[0m"

fi
