#!/usr/bin/env bash

echo "hoi"

if [ "$1" == "install" ]; then

    echo "install"

else

    echo '7lab'
    PROJECT_DIR=$(pwd)
    DOCKER_DIR="7lab-docker"

    if [ -d $DOCKER_DIR ]; then
        cd $DOCKER_DIR
        var="$(bash vessel \"$PROJECT_DIR\" \"$@\")"
        echo "$var"
        echo -e "$var"
        cd $PROJECT_DIR
    else
        echo -e "\033[31mNo '$DOCKER_DIR' directory found within current working directory '$PROJECT_DIR'\033[0m"
    fi

fi
